name: si_udin_app
description: A Flutter application for children to play and learn.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/tiger.png
    
  fonts:
    - family: Bubblegum
      fonts:
        - asset: assets/fonts/BubblegumSans-Regular.ttf